import tkinter as tk
from tkinter import ttk

window = tk.Tk()
window.geometry("600x400")
window.title("Search Operation")
window.configure(bg="grey")

search_label = tk.Label(window, bg="grey", fg="black", text = "Suchbegriff:", padx = 2, pady = 5)
search_label.grid(row=0, column=0, sticky="E")
search_entry = tk.Entry(window, width=75)
search_entry.grid(row=0, column=1, sticky="W")
inout_name_label = tk.Label(window, bg="grey", fg="black", text = "Eingang/Ausgang", padx = 1, pady = 5)
inout_name_label.grid(row=1, column=0, sticky="E")
inout_combo = ttk.Combobox(window, values=['Eingang', 'Ausgang'])
inout_combo.current(1)
inout_combo.grid(row=1, column=1, sticky="W")
category_label = tk.Label(window, bg="grey", fg="black", text = "Kategorie", padx = 1, pady = 5)
category_label.grid(row=2, column=0, sticky="E")
category_combo = ttk.Combobox(window, values=['Miete', 'Versicherung', 'Lebensmittel'])
category_combo.grid(row=2, column=1, sticky="W")
sum_name_label = tk.Label(window, bg="grey", fg="black", text = "Summe", padx = 1, pady = 5)
sum_name_label.grid(row=3, column=0, sticky="E")
sum_entry = tk.Entry(window, width=10)
sum_entry.grid(row=3, column=1, sticky="W")
date_label = tk.Label(window, bg="grey", fg="black", text = "Datum (DD.MM.YY)", padx = 1, pady = 5)
date_label.grid(row=4, column=0, sticky="E")
date_entry = tk.Entry(window, width=8)
date_entry.grid(row=4, column=1, sticky="W")
search_button = tk.Button(window, bg="orange", activebackground="red", fg="black", font="Arial 15", text="Suchen", padx=1, pady=5)
search_button.place(x=100, y=250)
cancel_button = tk.Button(window, bg="orange", fg="black", font="Arial 15", text="Abbrechen", padx=1, pady=5)
cancel_button.place(x=250, y=250)
